---
- hosts: all
  become: yes

  vars:
    requirements:
      - wget
      - git
      - net-tools
      - bind-utils
      - yum-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - kexec-tools
      - sos
      - psacct
      - docker-1.13.1

  tasks:

    - name: EPEL
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"

    - name: Origin Testing
      yum_repository:
        name: paas7-openshift-origin311-testing
        description: OpenShift Origin Testing
        baseurl: https://cbs.centos.org/repos/paas7-openshift-origin311-testing/$basearch/os/
        gpgcheck: no
      when: release == 'v3.11'

    - name: Requirements
      yum:
        name: "{{ requirements | join(',') }}"
        state: present

    - name: OpenShift Origin package
      yum:
        name: centos-release-openshift-origin
        state: present
      when: release != 'v3.11'

    - name: System upgrade
      yum: name=* state=latest update_cache=yes